//TEXTS
//https://coolors.co/2d2a3e-3e2f4b-5c3c64-8a538a-99628b-a7718b colors
const DEFAULT_HEADING_SIZE = 25;
const DEFAULT_SUB_HEADER_SIZE = 18;
const DEFAULT_TEXT_SIZE = 14;
const DEFAULT_TEXT_COLOR = '#EDDDD4';
//END-TEXTS
//APPS_CONSTS
const BACKGROUND_COLOR = '#264653';
//END_APPS_CONST

//COMPONENT CONSTS
const BUTTON_PRIMARY = '#81f7e9';
const BUTTON_SECONDARY = '#F4A261';
const BUTTON_DANGER = '#f04f26';

const BUTTON_TEXT_COLOR = '#30251f';
//END COMPONENTS CONSTS
export {
  DEFAULT_TEXT_SIZE,
  BACKGROUND_COLOR,
  DEFAULT_TEXT_COLOR,
  DEFAULT_HEADING_SIZE,
  DEFAULT_SUB_HEADER_SIZE,
  BUTTON_DANGER,
  BUTTON_SECONDARY,
  BUTTON_PRIMARY,
  BUTTON_TEXT_COLOR,
};
