//TEXTS
//https://coolors.co/2d2a3e-3e2f4b-5c3c64-8a538a-99628b-a7718b colors
const DEFAULT_HEADING_SIZE = 20;
const DEFAULT_SUB_HEADER_SIZE = 18;
const DEFAULT_TEXT_SIZE = 14;
const DEFAULT_TEXT_COLOR = '#fadeed';
//END-TEXTS
//APPS_CONSTS
const BACKGROUND_COLOR = '#2D2A3E';
//END_APPS_CONST
export {
  DEFAULT_TEXT_SIZE,
  BACKGROUND_COLOR,
  DEFAULT_TEXT_COLOR,
  DEFAULT_HEADING_SIZE,
  DEFAULT_SUB_HEADER_SIZE,
};
